### ISSUE TITLE
Liftover - MalformedURLException

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#81]
downloadLiftoverChainFiles leads to this error
```
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:644)
	at java.net.URL.<init>(URL.java:507)
	at java.net.URL.<init>(URL.java:456)
	at org.monarchinitiative.hpo_case_annotator.gui.controllers.SetResourcesController.downloadLiftoverChainFiles(SetResourcesController.java:451)
	(...)
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:549)
	... 118 more
```
However, the URL in hpo-case-annotator.properties appears to be OK
```
hg19.hg38.chain.url=https://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz
```

**Comment by ielis** [comment]
Yeah, you need to remove the properties file that is stored in `$HOME/.hpo.case.annotator/hpo-case-annotator.properties`. From some reason we need to remove the file and only after that start the app

**Comment by pnrobinson** [comment]
sorry, forgot. Works now!
